created login and register interface
dgmarulandac/PF_PTB_GRUPO_06 pull request #12
Opened 2023-08-11 22:01 UTC by Cristian-Massa

login and register interface connected with the backend.
Also have validator js archives.
React router dom, react redux index configure done.

2023-08-12 18:39 UTC, gabo963 requested changes

2023-08-12 18:39 UTC, gabo963 commented on client/src/functions/Validations/loginValidation/validation.js
> +    axios.get(`http://localhost:3001/usersCheck?displayName=${user}`)
Users check esta mal, deberia ser /users/check

2023-08-12 18:39 UTC, gabo963 commented on client/src/functions/Validations/registerValidation/validation.js
> +    axios.get(`http://localhost:3001/usersCheck?displayName=${user}&email=${email}`)
tambien /users/check

2023-08-12 18:45 UTC, Giann92 submitted a review, later dismissed

2023-08-12 18:59 UTC, Cristian-Massa commented on client/src/functions/Validations/loginValidation/validation.js
> +    axios.get(`http://localhost:3001/usersCheck?displayName=${user}`)
solucionado los dos

2023-08-12 22:51 UTC, gabo963 approved these changes
Ok

2023-08-12 22:59 UTC, hlrivero18 approved these changes

2023-08-12 23:09 UTC, merged

2023-08-13 01:32 UTC, Daniellg94 reviewed
ok